In [1]:
# Importing useful libraries

import pandas as pd
import numpy as np
import seaborn as sns
import sys
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import plotly.express as px

In [3]:
# Loading data to dataset

dataset = pd.read_excel(
    "./First Week of March.xlsx")
dataset.columns = dataset.iloc[0]
dataset = dataset[1:]
dataset

,PM_ID,PM_NAME,ACCOUNTING_PROVIDER,Trans #,Status,Initiation Date,Resident,Property,Ref ID,Unit,Primary Acct #,Bill Type,Amount,Payment Type,Payment Subtype,Transaction Schedule Type
1,96570549,Access Property Management,TOPS,342372637,Paid Out: 2023-03-09,2023-03-08T23:59:56Z,Carissa Stricker,Ferncroft Park,429,NaN,14979,Payment Amount,755.05,ACH,NaN,One Time Payment
2,100249094,WSR Real Estate,TOPS,342372562,Paid Out: 2023-03-09,2023-03-08T23:50:02Z,Melanie Treanor-Castro,Atherton Square Inc,25,NaN,8567,Payment Amount,190,ACH,NaN,One Time Payment
3,88219327,"Porto Bellagio Condominium Association, Inc.",TOPS,342372454,Paid Out: 2023-03-09,2023-03-08T23:38:55Z,Denis Yurov,Porto Bellagio CAI,PBC,NaN,469,Payment Amount,673.63,ACH,NaN,One Time Payment
4,89980784,Property Management One,TOPS,342372430,Paid Out: 2023-03-13,2023-03-08T23:36:23Z,Tim Nguyen,2827 Pine,2972,NaN,6221,Payment Amount,94.53,Credit,Visa (Credit),One Time Payment
5,78795237,"Property Keepers Management, LLC",TOPS,342372395,Paid Out: 2023-03-13,2023-03-08T23:33:13Z,Alcides Lorenzo Rodriguez,Walden Place Townhomes HOA,WPT,NaN,21224,Payment Amount,125,Credit,Discover (Credit),One Time Payment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176028,34140642,Fieldstone Association Management,TOPS,339108186,Paid Out: 2023-03-01,2023-03-01T00:11:50Z,Mikhaila and Marcus Wilkerson,White Oak at East Lake Townhome Association Inc,WEL,NaN,2775WOL@WEL,Payment Amount,165,ACH,NaN,One Time Payment
176029,73117821,Pacific Condo Strategies PLLC,TOPS,339108118,Paid Out: 2023-03-03,2023-03-01T00:09:26Z,Christopher Winchell,Village By The Lake Condominium Association,VL,NaN,2400,Payment Amount,526.06,ACH,NaN,One Time Payment
176030,47301165,Allied Property Group - TOPS PAY,TOPS,339107683,Paid Out: 2023-03-03,2023-03-01T00:02:50Z,Shelly Orjuelo,BAYSHORE YACHT AND TENNIS CLUB CONDO. ASSOC. INC.,140,NaN,63417,Payment Amount,1045.9,ACH,NaN,One Time Payment
176031,60756912,"Community Financials, Inc. (TOPS)",TOPS,339107537,Paid Out: 2023-03-01,2023-03-01T00:01:33Z,Mal (Shana) Kwon,Holgate Park Condominiums,T5074,NaN,5074000007@T5074,Amount Owed,235.03,ACH,NaN,One Time Payment
176032,36917242,Brickrow Property Management,TOPS,339107534,Paid Out: 2023-03-03,2023-03-01T00:00:59Z,Vanessa & Emma Rosa Villarreal,Bay Terrace Pines,BTP,NaN,6728@BTP,Payment Amount,900,Credit,Visa (Credit),One Time Payment

In [4]:
dataset["Initiation Date"] = pd.to_datetime(
    dataset["Initiation Date"], format="ISO8601")
dataset

,PM_ID,PM_NAME,ACCOUNTING_PROVIDER,Trans #,Status,Initiation Date,Resident,Property,Ref ID,Unit,Primary Acct #,Bill Type,Amount,Payment Type,Payment Subtype,Transaction Schedule Type
1,96570549,Access Property Management,TOPS,342372637,Paid Out: 2023-03-09,2023-03-08 23:59:56+00:00,Carissa Stricker,Ferncroft Park,429,NaN,14979,Payment Amount,755.05,ACH,NaN,One Time Payment
2,100249094,WSR Real Estate,TOPS,342372562,Paid Out: 2023-03-09,2023-03-08 23:50:02+00:00,Melanie Treanor-Castro,Atherton Square Inc,25,NaN,8567,Payment Amount,190,ACH,NaN,One Time Payment
3,88219327,"Porto Bellagio Condominium Association, Inc.",TOPS,342372454,Paid Out: 2023-03-09,2023-03-08 23:38:55+00:00,Denis Yurov,Porto Bellagio CAI,PBC,NaN,469,Payment Amount,673.63,ACH,NaN,One Time Payment
4,89980784,Property Management One,TOPS,342372430,Paid Out: 2023-03-13,2023-03-08 23:36:23+00:00,Tim Nguyen,2827 Pine,2972,NaN,6221,Payment Amount,94.53,Credit,Visa (Credit),One Time Payment
5,78795237,"Property Keepers Management, LLC",TOPS,342372395,Paid Out: 2023-03-13,2023-03-08 23:33:13+00:00,Alcides Lorenzo Rodriguez,Walden Place Townhomes HOA,WPT,NaN,21224,Payment Amount,125,Credit,Discover (Credit),One Time Payment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176028,34140642,Fieldstone Association Management,TOPS,339108186,Paid Out: 2023-03-01,2023-03-01 00:11:50+00:00,Mikhaila and Marcus Wilkerson,White Oak at East Lake Townhome Association Inc,WEL,NaN,2775WOL@WEL,Payment Amount,165,ACH,NaN,One Time Payment
176029,73117821,Pacific Condo Strategies PLLC,TOPS,339108118,Paid Out: 2023-03-03,2023-03-01 00:09:26+00:00,Christopher Winchell,Village By The Lake Condominium Association,VL,NaN,2400,Payment Amount,526.06,ACH,NaN,One Time Payment
176030,47301165,Allied Property Group - TOPS PAY,TOPS,339107683,Paid Out: 2023-03-03,2023-03-01 00:02:50+00:00,Shelly Orjuelo,BAYSHORE YACHT AND TENNIS CLUB CONDO. ASSOC. INC.,140,NaN,63417,Payment Amount,1045.9,ACH,NaN,One Time Payment
176031,60756912,"Community Financials, Inc. (TOPS)",TOPS,339107537,Paid Out: 2023-03-01,2023-03-01 00:01:33+00:00,Mal (Shana) Kwon,Holgate Park Condominiums,T5074,NaN,5074000007@T5074,Amount Owed,235.03,ACH,NaN,One Time Payment
176032,36917242,Brickrow Property Management,TOPS,339107534,Paid Out: 2023-03-03,2023-03-01 00:00:59+00:00,Vanessa & Emma Rosa Villarreal,Bay Terrace Pines,BTP,NaN,6728@BTP,Payment Amount,900,Credit,Visa (Credit),One Time Payment

In [6]:
# Adding month and year and set up previsors and aimed results

dataset['month'] = dataset['Initiation Date'].dt.month
dataset['year'] = dataset['Initiation Date'].dt.year

previsors = dataset.iloc[:, [ 12, 13, 16, 17]].values
results = dataset.iloc[:, 15].values

print(previsors, results)

[[755.05 'ACH' 3 2023]
 [190 'ACH' 3 2023]
 [673.63 'ACH' 3 2023]
 ...
 [1045.9 'ACH' 3 2023]
 [235.03 'ACH' 3 2023]
 [900 'Credit' 3 2023]] ['One Time Payment' 'One Time Payment' 'One Time Payment' ...
 'One Time Payment' 'One Time Payment' 'One Time Payment']

In [9]:
# Convertendo o que for string para alguma coisa relacionada a um numero

labelencoder_teste = LabelEncoder()
previsors[:, 1] = labelencoder_teste.fit_transform(previsors[:, 1])

previsors

array([[755.05, 0, 0, 2023],
       [190, 0, 0, 2023],
       [673.63, 0, 0, 2023],
       ...,
       [1045.9, 0, 0, 2023],
       [235.03, 0, 0, 2023],
       [900, 2, 0, 2023]], dtype=object)

In [1]:
# Criando um escalonamento dos dados para que possa ser feito os calculos nos nossos algoritmos

scaler_data = StandardScaler()
previsors = scaler_data.fit_transform(previsors)
previsors[0]

NameError: name 'StandardScaler' is not defined

In [ ]:
# Divinding the bases
from sklearn.model_selection import train_test_split

previsors_test, previsors_train, classe_test, classe_train = train_test_split(
    previsors, results, test_size=0.60, random_state=0)
previsors_train.shape, classe_train.shape

((105620, 4), (105620,))

In [ ]:
# Saving the database
import pickle

with open('./zegodata.pkl', mode='wb') as f:
    pickle.dump([previsors_train, classe_train], f)

with open('./zegotestdata.pkl', mode='wb') as arquivo:
    pickle.dump([previsors_test, classe_test], arquivo)

In [ ]:
from sklearn.naive_bayes import GaussianNB

naive_recurrence = GaussianNB()
naive_recurrence.fit(previsors_train, classe_train)
prevision = naive_recurrence.predict(previsors_test)
sns.countplot(x=prevision)

In [ ]:
# Verifying accuracy

from sklearn.metrics import accuracy_score, confusion_matrix
from yellowbrick.classifier import ConfusionMatrix
confusion_matrix(classe_test, prevision)
cm  = ConfusionMatrix(naive_recurrence)
cm.fit(previsors_train, classe_train)
cm.score(previsors_test, classe_test)

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(classe_test, prevision))

In [ ]:
# Arvores de decisÃ£o

from sklearn.tree import DecisionTreeClassifier

# quando utilizamos o objeto DecisionTreeClassifier, temos que definir o criterion de entropia e realizar novamente o aprendizado com o .fit

decisiontree = DecisionTreeClassifier(criterion='entropy')
decisiontree.fit(previsors_train, classe_train)

In [ ]:
decisiontree.feature_importances_

In [ ]:
from sklearn import tree

# Aqui estamos plotando a arvore de decisÃ£o
previsores = ['Valores', 'Tipo de Pagamento', 'Mes', "Ano"]
figura, eixos = plt.subplots(ncols=1, nrows=1)
tree.plot_tree(decisiontree)

In [2]:
previsao = decisiontree.predict(previsors_train)
previsao

from sklearn.metrics import accuracy_score, confusion_matrix
from yellowbrick.classifier import ConfusionMatrix
confusion_matrix(classe_test, previsao)
cm  = ConfusionMatrix(naive_recurrence)
cm.fit(previsors_train, classe_train)
cm.score(previsors_test, classe_test)

NameError: name 'decisiontree' is not defined